apiVersion: v1
kind: Service
metadata:
  name: hotels
  namespace: ekioba
  labels:
    app: hotels
    app.kubernetes.io/part-of: ekioba
spec:
  type: ClusterIP
  selector:
    app: hotels
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP
