name: ekioba
services:
  - name: backend
    image:
      registry: docker.io
      repository: __DOCKER_USERNAME__/backend
      tag: latest
    envs:
      - key: DJANGO_SECRET_KEY
        value: ${DJANGO_SECRET_KEY}
        type: SECRET
      - key: STORE_URL
        value: ${STORE_URL}
        type: SECRET
      - key: HOTELS_URL
        value: ${HOTELS_URL}
        type: SECRET
      - key: TON_API_KEY
        value: ${TON_API_KEY}
        type: SECRET
      - key: SOLANA_API_KEY
        value: ${SOLANA_API_KEY}
        type: SECRET
    http_port: 8000
  - name: frontend
    image:
      registry: docker.io
      repository: __DOCKER_USERNAME__/frontend
      tag: latest
    http_port: 3000
    envs:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: "https://python-api-653036098161.us-central1.run.app"
