name: my-app
services:
  - name: backend
    image:
      registry: docker.io
      repository: <DOCKER_USERNAME>/backend
      tag: latest
    http_port: 8000
    envs:
      - key: DJANGO_SECRET_KEY
        value: ${DJANGO_SECRET_KEY}
        type: SECRET
      - key: STORE_URL
        value: ${STORE_URL}
        type: SECRET
      - key: HOTELS_URL
        value: ${HOTELS_URL}
        type: SECRET
      - key: TON_API_KEY
        value: ${TON_API_KEY}
        type: SECRET
      - key: SOLANA_API_KEY
        value: ${SOLANA_API_KEY}
        type: SECRET
  - name: frontend
    image:
      registry: docker.io
      repository: <DOCKER_USERNAME>/frontend
      tag: latest
    http_port: 3000
    envs:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: "https://python-api-653036098161.us-central1.run.app"
