# GENERATED by scripts/sync_knowledge_base.py from ai_assistant/app/knowledge_base.py.
# Edit that file and rerun the script; changes made here are overwritten.

"""
Knowledge Base retrieval for Iyobo.

The EKIOBA Knowledge Base (the repo's "Knowledge Base" folder) is Iyobo's main source.
Markdown is split into sections at its headings and JSON into one chunk per record, so a
single vocabulary row can be retrieved on its own. Chunks are ranked with BM25 over
tokens with tone marks and subdots removed, so "ewe" finds "Ẹwẹ".
"""

from __future__ import annotations

import json
import logging
import math
import re
import unicodedata
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Iterator, Optional

logger = logging.getLogger("iyobo-service.knowledge_base")

# Repo checkout: ai_assistant/app/knowledge_base.py -> <repo>/Knowledge Base
REPO_KNOWLEDGE_BASE = Path(__file__).resolve().parents[2] / "Knowledge Base"
# Container: docker-compose mounts the folder here.
CONTAINER_KNOWLEDGE_BASE = Path("/app/knowledge_base")

INDEXED_SUFFIXES = (".md", ".json")
MAX_CHUNK_CHARS = 1800

# BM25 parameters (the usual defaults).
_K1 = 1.5
_B = 0.75

# Phrase matching: a run of consecutive query words (common words included) found verbatim in a
# chunk earns a bonus per word. Without it "What is this?" finds nothing, because every word is
# a stopword, yet the Academy has a phrase with exactly that meaning.
MIN_PHRASE_WORDS = 3
MAX_PHRASE_WORDS = 8
PHRASE_BONUS_PER_WORD = 2.0

_TOKEN_RE = re.compile(r"[a-z0-9]+")
_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*#*\s*$")
_STOPWORDS = frozenset(
    "a about an and are as at be but by can do does for from how in is it me my of on or "
    "please say tell that the this to was what when where which who why will with you your".split()
)


@dataclass(frozen=True)
class Chunk:
    source: str  # path relative to the Knowledge Base root, e.g. "Language Academy/edo-animals-dataset.json"
    title: str  # heading path for Markdown, record path for JSON; may be empty
    text: str


def normalize(text: str) -> str:
    """Lower-case and strip combining marks (tone marks, subdots, umlauts)."""
    decomposed = unicodedata.normalize("NFKD", text.lower())
    return "".join(ch for ch in decomposed if not unicodedata.combining(ch))


def tokenize(text: str) -> list[str]:
    return [
        token
        for token in _TOKEN_RE.findall(normalize(text))
        if len(token) > 1 and token not in _STOPWORDS
    ]


def _phrase_text(text: str) -> str:
    """All words, stopwords included, space-padded so phrase lookups match whole words."""
    return f" {' '.join(_TOKEN_RE.findall(normalize(text)))} "


def _query_phrases(query: str) -> list[tuple[str, int]]:
    """Runs of MIN..MAX consecutive query words made only of stopwords, longest first.

    Only all-stopword runs ("what is this") qualify: BM25 already scores phrases that contain
    real terms, and boosting those lets question framing like "edo word for" drown the answer.
    Returns (space-padded phrase, word count) pairs.
    """
    words = _TOKEN_RE.findall(normalize(query))
    phrases: dict[str, int] = {}
    for size in range(min(len(words), MAX_PHRASE_WORDS), MIN_PHRASE_WORDS - 1, -1):
        for start in range(len(words) - size + 1):
            run = words[start : start + size]
            if all(word in _STOPWORDS for word in run):
                phrases.setdefault(f" {' '.join(run)} ", size)
    return sorted(phrases.items(), key=lambda item: -item[1])


def resolve_root(configured: str = "") -> Optional[Path]:
    """Return the configured Knowledge Base folder, else the first default location that exists."""
    if configured.strip():
        return Path(configured.strip())
    for candidate in (REPO_KNOWLEDGE_BASE, CONTAINER_KNOWLEDGE_BASE):
        if candidate.is_dir():
            return candidate
    return None


def _pieces(body: str) -> Iterator[str]:
    """Yield paragraphs; oversized paragraphs (e.g. long tables) are broken at line ends."""
    for paragraph in re.split(r"\n\s*\n", body):
        paragraph = paragraph.strip()
        if len(paragraph) <= MAX_CHUNK_CHARS:
            if paragraph:
                yield paragraph
            continue
        for line in paragraph.splitlines():
            for start in range(0, len(line), MAX_CHUNK_CHARS):
                yield line[start : start + MAX_CHUNK_CHARS]


def _split_long(source: str, title: str, body: str) -> list[Chunk]:
    if len(body) <= MAX_CHUNK_CHARS:
        return [Chunk(source, title, body)]
    chunks: list[Chunk] = []
    current = ""
    for piece in _pieces(body):
        if current and len(current) + len(piece) + 1 > MAX_CHUNK_CHARS:
            chunks.append(Chunk(source, title, current))
            current = piece
        else:
            current = f"{current}\n{piece}" if current else piece
    if current:
        chunks.append(Chunk(source, title, current))
    return chunks


def _markdown_chunks(source: str, text: str) -> list[Chunk]:
    chunks: list[Chunk] = []
    headings: list[tuple[int, str]] = []
    lines: list[str] = []
    in_code = False

    def flush() -> None:
        body = "\n".join(lines).strip()
        lines.clear()
        if body:
            title = " > ".join(heading for _, heading in headings)
            chunks.extend(_split_long(source, title, body))

    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            in_code = not in_code
        match = None if in_code else _HEADING_RE.match(line)
        if match:
            flush()
            level = len(match.group(1))
            while headings and headings[-1][0] >= level:
                headings.pop()
            headings.append((level, match.group(2)))
        else:
            lines.append(line)
    flush()
    return chunks


def _render(value: Any) -> str:
    if isinstance(value, dict):
        return "; ".join(
            f"{key}: {_render(item)}" for key, item in value.items() if item not in (None, "", [], {})
        )
    if isinstance(value, list):
        return ", ".join(_render(item) for item in value)
    return str(value)


def _json_chunks(source: str, data: Any) -> list[Chunk]:
    chunks: list[Chunk] = []

    def walk(node: Any, path: str) -> None:
        if isinstance(node, list):
            if node and all(isinstance(item, dict) for item in node):
                for item in node:  # one chunk per record
                    chunks.extend(_split_long(source, path, _render(item)))
            elif node:
                chunks.extend(_split_long(source, path, _render(node)))
            return
        if isinstance(node, dict):
            nested = {
                key: value
                for key, value in node.items()
                if isinstance(value, dict)
                or (isinstance(value, list) and any(isinstance(item, (dict, list)) for item in value))
            }
            leaves = {key: value for key, value in node.items() if key not in nested}
            rendered = _render(leaves)
            if rendered:
                chunks.extend(_split_long(source, path, rendered))
            for key, value in nested.items():
                walk(value, f"{path}.{key}" if path else key)
            return
        if node not in (None, ""):
            chunks.extend(_split_long(source, path, str(node)))

    walk(data, "")
    return chunks


def _is_excluded(relative_path: str, excluded: set[str]) -> bool:
    lowered = relative_path.lower()
    return any(lowered == entry or lowered.startswith(entry + "/") for entry in excluded)


class KnowledgeBase:
    """An in-memory BM25 index over the Knowledge Base's Markdown and JSON files."""

    def __init__(self, root: Optional[Path], chunks: list[Chunk]):
        self.root = root
        self.chunks = chunks
        self._term_counts = [
            Counter(tokenize(f"{chunk.source}\n{chunk.title}\n{chunk.text}")) for chunk in chunks
        ]
        self._phrase_texts = [_phrase_text(chunk.text) for chunk in chunks]
        self._lengths = [sum(counts.values()) for counts in self._term_counts]
        self._average_length = (sum(self._lengths) / len(self._lengths)) if chunks else 0.0
        document_frequency: Counter[str] = Counter()
        for counts in self._term_counts:
            document_frequency.update(counts.keys())
        total = len(chunks)
        self._idf = {
            term: math.log(1 + (total - frequency + 0.5) / (frequency + 0.5))
            for term, frequency in document_frequency.items()
        }

    @property
    def sources(self) -> list[str]:
        return sorted({chunk.source for chunk in self.chunks})

    @classmethod
    def load(cls, root: Optional[Path], exclude: Iterable[str] = ()) -> "KnowledgeBase":
        if root is None or not root.is_dir():
            logger.warning("Knowledge Base folder not found (%s); Iyobo will rely on web search", root)
            return cls(root, [])

        excluded = {entry.strip().strip("/\\").lower() for entry in exclude if entry.strip()}
        chunks: list[Chunk] = []
        for path in sorted(root.rglob("*")):
            if not path.is_file() or path.suffix.lower() not in INDEXED_SUFFIXES:
                continue
            relative_path = path.relative_to(root).as_posix()
            if _is_excluded(relative_path, excluded):
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError) as exc:
                logger.warning("Skipping unreadable Knowledge Base file %s: %s", relative_path, exc)
                continue
            if path.suffix.lower() == ".md":
                chunks.extend(_markdown_chunks(relative_path, text))
                continue
            try:
                chunks.extend(_json_chunks(relative_path, json.loads(text)))
            except json.JSONDecodeError as exc:
                logger.warning("Skipping invalid JSON in Knowledge Base file %s: %s", relative_path, exc)

        logger.info("Knowledge Base loaded: %d chunks from %s", len(chunks), root)
        return cls(root, chunks)

    def search(self, query: str, limit: int = 6) -> list[tuple[Chunk, float]]:
        terms = set(tokenize(query))
        phrases = _query_phrases(query)
        if not self.chunks or not (terms or phrases):
            return []
        scored: list[tuple[float, int]] = []
        for index, counts in enumerate(self._term_counts):
            score = 0.0
            length_norm = _K1 * (1 - _B + _B * self._lengths[index] / self._average_length)
            for term in terms:
                frequency = counts.get(term)
                if frequency:
                    score += self._idf[term] * frequency * (_K1 + 1) / (frequency + length_norm)
            for phrase, length in phrases:  # longest first; only the best match counts
                if phrase in self._phrase_texts[index]:
                    score += PHRASE_BONUS_PER_WORD * length
                    break
            if score > 0:
                scored.append((score, index))
        scored.sort(key=lambda item: (-item[0], item[1]))
        return [(self.chunks[index], score) for score, index in scored[:limit]]


def format_context(hits: list[tuple[Chunk, float]], max_chars: int) -> tuple[str, list[str]]:
    """Render hits as labelled [KBn] excerpts within a character budget.

    Returns the excerpt text and the source files that made it in.
    """
    blocks: list[str] = []
    sources: list[str] = []
    used = 0
    for number, (chunk, _score) in enumerate(hits, start=1):
        label = f"{chunk.source} — {chunk.title}" if chunk.title else chunk.source
        block = f"[KB{number}] {label}\n{chunk.text}"
        if blocks and used + len(block) > max_chars:
            break
        blocks.append(block[:max_chars])
        used += len(block)
        if chunk.source not in sources:
            sources.append(chunk.source)
    return "\n\n".join(blocks), sources
