"""
Write the knowledge suggestions the owner approved into the Knowledge Base files.

Approved suggestions are already searchable by Iyobo. Exporting them makes them part of the
Knowledge Base itself, so the website's offline answers, the Academy and the Supabase vocabulary
table get them too:

    entries with an Edo word and meaning -> Knowledge Base/Language Academy/edo-learned-dataset.json
    everything else                      -> Knowledge Base/Iyobo Learned/approved-notes.md

Reads IYOBO_MEMORY_DB_URL, DATABASE_URL or SUPABASE_DB_URL from the environment, falling back to
ai_assistant/.env. Afterwards run scripts/sync_knowledge_base.py, and load_edo_vocabulary.py to
update Supabase.

Usage:
    python scripts/export_learned_knowledge.py
    python scripts/export_learned_knowledge.py --dry-run
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AI_DIR = REPO_ROOT / "ai_assistant"
ENV_FILE = AI_DIR / ".env"
DATASET = REPO_ROOT / "Knowledge Base" / "Language Academy" / "edo-learned-dataset.json"
NOTES = REPO_ROOT / "Knowledge Base" / "Iyobo Learned" / "approved-notes.md"

sys.path.insert(0, str(AI_DIR))


def _setting(name: str) -> str:
    value = os.getenv(name, "").strip()
    if value or not ENV_FILE.is_file():
        return value
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        if line.startswith(f"{name}="):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    return ""


async def load_approved(database_url: str) -> list[dict]:
    from app.learning_store import LearningStore

    # The salt only matters when recording suggestions, not when reading them.
    store = LearningStore(database_url, user_id_salt="export")
    try:
        return await store.approved()
    finally:
        await store.close()


def build_outputs(rows: list[dict]) -> tuple[dict, str]:
    words = sorted((r for r in rows if r.get("edo") and r.get("english")), key=lambda r: r["id"])
    notes = sorted((r for r in rows if not (r.get("edo") and r.get("english"))), key=lambda r: r["id"])

    dataset = {
        "source": {
            "title": "Knowledge taught to Iyobo and approved by the EKIOBA team",
            "note": "Generated by scripts/export_learned_knowledge.py from the approved review queue. Edit the queue, not this file.",
            "language": "Edo (Bini), Niger-Congo; main language of the ancient Kingdom of Benin",
        },
        "academy_vocabulary": [
            {
                "edo": r["edo"],
                "english": r["english"],
                "category": r.get("category") or "general",
                "example": r.get("example") or f"{r['edo']} — {r['english']}",
                "suggestion_id": r["id"],
            }
            for r in words
        ],
    }

    lines = [
        "# Approved Notes Taught to Iyobo",
        "",
        "Things users taught Iyobo that the EKIOBA team reviewed and approved, other than single Edo words",
        "(those are in the Language Academy's edo-learned dataset). Generated by",
        "scripts/export_learned_knowledge.py; edit the review queue, not this file.",
        "",
    ]
    for r in notes:
        reviewed = r.get("reviewed_at")
        when = reviewed.date().isoformat() if hasattr(reviewed, "date") else str(reviewed or "")[:10]
        lines += [f"## Suggestion {r['id']}", "", r["note"], ""]
        if r.get("reviewer_note"):
            lines += [f"- Reviewer's note: {r['reviewer_note']}"]
        lines += [f"- Approved: {when or 'unknown date'}", ""]
    if not notes:
        lines.append("No approved notes yet.")
    return dataset, "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true", help="Show what would be written without writing files.")
    args = parser.parse_args()

    database_url = _setting("IYOBO_MEMORY_DB_URL") or _setting("DATABASE_URL") or _setting("SUPABASE_DB_URL")
    if not database_url:
        print("No database URL: set IYOBO_MEMORY_DB_URL, DATABASE_URL or SUPABASE_DB_URL.", file=sys.stderr)
        return 1

    rows = asyncio.run(load_approved(database_url))
    dataset, notes_markdown = build_outputs(rows)
    word_count = len(dataset["academy_vocabulary"])
    print(f"{len(rows)} approved suggestions: {word_count} words, {len(rows) - word_count} notes")
    if args.dry_run:
        for entry in dataset["academy_vocabulary"][:10]:
            print(f"  word: {entry['edo']} — {entry['english']}")
        return 0

    DATASET.write_text(json.dumps(dataset, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    NOTES.parent.mkdir(parents=True, exist_ok=True)
    NOTES.write_text(notes_markdown, encoding="utf-8")
    print(f"Wrote {DATASET.relative_to(REPO_ROOT)} and {NOTES.relative_to(REPO_ROOT)}.")
    print("Next: python scripts/sync_knowledge_base.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
