"""
Copy the Knowledge Base into the frontend so the site chat can answer from it offline.

Vercel deploys only frontend/, and the frontend Docker image is built from frontend/, so neither
can read the repo's "Knowledge Base" folder. This script copies:

    Knowledge Base/**/*.md and *.json (minus infrastructure docs)  ->  frontend/knowledge_base/
    ai_assistant/app/knowledge_base.py (the search code)            ->  frontend/services/knowledge_base.py

Run it after editing the Knowledge Base or the search code, and commit the result. With --check
it changes nothing and exits 1 if the frontend copy is out of date (CI runs this).

Usage:
    python scripts/sync_knowledge_base.py
    python scripts/sync_knowledge_base.py --check
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / "Knowledge Base"
SNAPSHOT_DIR = REPO_ROOT / "frontend" / "knowledge_base"
SEARCH_SOURCE = REPO_ROOT / "ai_assistant" / "app" / "knowledge_base.py"
SEARCH_COPY = REPO_ROOT / "frontend" / "services" / "knowledge_base.py"

# Mirrors the KNOWLEDGE_BASE_EXCLUDE default in ai_assistant/config.py: infrastructure docs stay
# out of anything the public site can quote.
EXCLUDE = ("SECURITY.md", "DEPLOYMENT.md", "Supabase")
INDEXED_SUFFIXES = (".md", ".json")

GENERATED_HEADER = (
    "# GENERATED by scripts/sync_knowledge_base.py from ai_assistant/app/knowledge_base.py.\n"
    "# Edit that file and rerun the script; changes made here are overwritten.\n\n"
)


def _is_excluded(relative_path: str) -> bool:
    lowered = relative_path.lower()
    return any(lowered == entry.lower() or lowered.startswith(entry.lower() + "/") for entry in EXCLUDE)


def expected_files() -> dict[Path, bytes]:
    """Every file the frontend copy should contain, with its exact contents."""
    files: dict[Path, bytes] = {}
    for path in sorted(SOURCE_DIR.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in INDEXED_SUFFIXES:
            continue
        relative_path = path.relative_to(SOURCE_DIR).as_posix()
        if not _is_excluded(relative_path):
            files[SNAPSHOT_DIR / relative_path] = path.read_bytes()
    files[SEARCH_COPY] = GENERATED_HEADER.encode("utf-8") + SEARCH_SOURCE.read_bytes()
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Report whether the copy is current; change nothing.")
    args = parser.parse_args()

    expected = expected_files()
    changed = [path for path, data in expected.items() if not path.is_file() or path.read_bytes() != data]
    leftover = (
        [path for path in SNAPSHOT_DIR.rglob("*") if path.is_file() and path not in expected]
        if SNAPSHOT_DIR.is_dir()
        else []
    )

    if args.check:
        if not changed and not leftover:
            print("Frontend Knowledge Base copy is up to date.")
            return 0
        for path in changed:
            print(f"  out of date: {path.relative_to(REPO_ROOT)}")
        for path in leftover:
            print(f"  no longer in the Knowledge Base: {path.relative_to(REPO_ROOT)}")
        print("Run: python scripts/sync_knowledge_base.py", file=sys.stderr)
        return 1

    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(expected[path])
        print(f"  updated: {path.relative_to(REPO_ROOT)}")
    for path in leftover:
        path.unlink()
        print(f"  removed: {path.relative_to(REPO_ROOT)}")
    print(f"Done. {len(expected) - 1} Knowledge Base files in {SNAPSHOT_DIR.relative_to(REPO_ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
