"""
Copy the Knowledge Base and Iyobo's shared answer code into the frontend.

Vercel and the frontend Docker image can't import the AI assistant's code or read the repo's
"Knowledge Base" folder the way the assistant does. This script copies:

    Knowledge Base/**/*.md and *.json (minus infrastructure docs)  ->  frontend/knowledge_base/
                                                                        ai_assistant/knowledge_base/
    ai_assistant/app/<shared module>.py                             ->  frontend/services/<same name>

The ai_assistant copy is for the assistant's Vercel service, which only ships the ai_assistant folder.

The shared modules are the Knowledge Base search, the Grok client, the web check against the
Knowledge Base, and answering without memory. The site chat quotes the Knowledge Base when no AI is
available, and uses these modules to ask Grok directly when no assistant service is deployed.

Run it after editing the Knowledge Base or a shared module, and commit the result. With --check
it changes nothing and exits 1 if the frontend copy is out of date (CI runs this).

Usage:
    python scripts/sync_knowledge_base.py
    python scripts/sync_knowledge_base.py --check
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / "Knowledge Base"
SNAPSHOT_DIR = REPO_ROOT / "frontend" / "knowledge_base"
ASSISTANT_SNAPSHOT_DIR = REPO_ROOT / "ai_assistant" / "knowledge_base"
SNAPSHOT_DIRS = (SNAPSHOT_DIR, ASSISTANT_SNAPSHOT_DIR)
ASSISTANT_APP = REPO_ROOT / "ai_assistant" / "app"
FRONTEND_SERVICES = REPO_ROOT / "frontend" / "services"

# Assistant modules the website runs unchanged. They may only import each other (as `app.<name>`),
# which becomes `services.<name>` in the copy.
SHARED_MODULES = ("knowledge_base.py", "grok_client.py", "web_verification.py", "stateless_answer.py")

# Mirrors the KNOWLEDGE_BASE_EXCLUDE default in ai_assistant/config.py: documents written for
# whoever builds EKIOBA stay out of anything the public site can quote. A visitor asking "tell me
# about the app" was being answered with the wallet dashboard's API endpoints and JSON schemas.
EXCLUDE = (
    # Infrastructure.
    "SECURITY.md",
    "DEPLOYMENT.md",
    "Supabase",
    # Written for developers, not visitors.
    "README.md",
    "INDEX.md",
    "AGENT_INSTRUCTIONS.md",
    "WALLET_DASHBOARD_INTEGRATION.md",
    "Project Readmes",
)
INDEXED_SUFFIXES = (".md", ".json")


def _is_excluded(relative_path: str) -> bool:
    lowered = relative_path.lower()
    return any(lowered == entry.lower() or lowered.startswith(entry.lower() + "/") for entry in EXCLUDE)


def _shared_module_copy(name: str) -> bytes:
    header = (
        f"# GENERATED by scripts/sync_knowledge_base.py from ai_assistant/app/{name}.\n"
        "# Edit that file and rerun the script; changes made here are overwritten.\n\n"
    )
    source = (ASSISTANT_APP / name).read_text(encoding="utf-8")
    # The assistant's package is `app`; on the website the same modules live in `services`.
    return (header + source.replace("from app.", "from services.")).encode("utf-8")


def expected_files() -> dict[Path, bytes]:
    """Every file the frontend copy should contain, with its exact contents."""
    files: dict[Path, bytes] = {}
    for path in sorted(SOURCE_DIR.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in INDEXED_SUFFIXES:
            continue
        relative_path = path.relative_to(SOURCE_DIR).as_posix()
        if not _is_excluded(relative_path):
            data = path.read_bytes()
            for snapshot_dir in SNAPSHOT_DIRS:
                files[snapshot_dir / relative_path] = data
    for name in SHARED_MODULES:
        files[FRONTEND_SERVICES / name] = _shared_module_copy(name)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Report whether the copy is current; change nothing.")
    args = parser.parse_args()

    expected = expected_files()
    changed = [path for path, data in expected.items() if not path.is_file() or path.read_bytes() != data]
    leftover = [
        path
        for snapshot_dir in SNAPSHOT_DIRS
        if snapshot_dir.is_dir()
        for path in snapshot_dir.rglob("*")
        if path.is_file() and path not in expected
    ]

    if args.check:
        if not changed and not leftover:
            print("Frontend Knowledge Base copy is up to date.")
            return 0
        for path in changed:
            print(f"  out of date: {path.relative_to(REPO_ROOT)}")
        for path in leftover:
            print(f"  no longer in the Knowledge Base: {path.relative_to(REPO_ROOT)}")
        print("Run: python scripts/sync_knowledge_base.py", file=sys.stderr)
        return 1

    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(expected[path])
        print(f"  updated: {path.relative_to(REPO_ROOT)}")
    for path in leftover:
        path.unlink()
        print(f"  removed: {path.relative_to(REPO_ROOT)}")
    knowledge_files = (len(expected) - len(SHARED_MODULES)) // len(SNAPSHOT_DIRS)
    folders = " and ".join(str(snapshot_dir.relative_to(REPO_ROOT)) for snapshot_dir in SNAPSHOT_DIRS)
    print(f"Done. {knowledge_files} Knowledge Base files in {folders}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
