name: DigitalOcean CD

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to DigitalOcean
        run: doctl auth init -t ${{ secrets.DO_API_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t azawalletekioba/ekioba:edomall \
            -t azawalletekioba/ekioba:latest \
            -f Dockerfile.universal . --push

      - name: Deploy to DigitalOcean App Platform
        run: doctl apps update ekioba-universal --spec app.yaml
