- name: Run Tests
  working-directory: store
  env:
    DJANGO_DB_ENGINE: ${{ vars.DJANGO_DB_ENGINE }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    TON_API_KEY: ${{ secrets.TON_API_KEY }}
    SOLANA_API_KEY: ${{ secrets.SOLANA_API_KEY }}
  run: |
    python manage.py test
